
server:
  port: 0
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/home_group_db
    username: root
    password: root
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
jwt:
  secret: apple
